const 

SELECCIONAR_CLIENTE  = "SELECCIONAR_CLIENTE",
SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO",
CANTIDAD_PRODUCTOS   = "CANTIDAD_PRODUCTOS",
ACTUALIZAR_TOTAL     = "ACTUALIZAR_TOTAL";

export { 

    SELECCIONAR_CLIENTE, 
    SELECCIONAR_PRODUCTO, 
    CANTIDAD_PRODUCTOS, 
    ACTUALIZAR_TOTAL 

};